export const WORKSPACE_TAB_EMPTY_WIDTH = 88;
export const WORKSPACE_TAB_MIN_WIDTH = 48;
export const WORKSPACE_TAB_MAX_WIDTH = 132;
export const WORKSPACE_TAB_INNER_PADDING = 8;
export const WORKSPACE_TAB_GAP = 4;
export const WORKSPACE_TAB_TRAILING_CUSHION = 10;
