export const WORKSPACE_TAB_EMPTY_WIDTH = 88;
export const WORKSPACE_TAB_MIN_WIDTH = 48;
export const WORKSPACE_TAB_MAX_WIDTH_APP = 220;
export const WORKSPACE_TAB_MAX_WIDTH_WORKSPACE = 180;
export const WORKSPACE_TAB_GAP = 4;
